# Generated by Django 3.1.2 on 2020-11-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201104_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pin',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
