# Generated by Django 3.1.2 on 2020-11-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('note', models.TextField(verbose_name='Advert Note')),
                ('img', models.ImageField(null=True, upload_to='')),
                ('url', models.URLField(null=True)),
            ],
        ),
    ]
