# Generated by Django 3.1.2 on 2020-11-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='img',
            field=models.ImageField(null=True, upload_to='advert'),
        ),
    ]
