# Generated by Django 3.1.2 on 2020-11-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_auto_20201103_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
