# Generated by Django 3.1.2 on 2020-11-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0003_advert_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='status',
            field=models.SmallIntegerField(default=1, verbose_name=''),
        ),
    ]
