# Generated by Django 3.1.2 on 2020-11-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0004_auto_20201103_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1),
        ),
    ]
